[package]
name = "this-error-from-box"
description = "Generates From impls for boxed thiserror enum variants"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = "2.0.106"

[dev-dependencies]
thiserror = "2.0.16"
